### PR TITLE
Add GitHub Codespace environment

### PR DESCRIPTION
**Pull request by kabilar**
- [x] Add Codespace devcontainers from `minimal` branch
  - [x] Commented CaImAn installation due to reaching Docker image size limits on Codespace
  - [x] Update python base image to version 3.9 due to suite2p dependency (i.e. scipy) error for python version 3.7
- [x] Update README with description of interactive tutorial on GitHub Codespaces
- [x] Remove notebooks in anticipation of tutorial revamp
- [x] Update requirements

### CODE REVIEW

**Review by kushalbakshi — APPROVED** [review]

**Review by kushalbakshi — COMMENTED** [review]
The changes look good, @kabilar. However, in local testing, I'm still getting an error that suite2p is not installed. On GitHub, I'm not able to select a Python kernel that can run DataJoint. Please see the screenshot below for the error in GitHub. 

image

**Comment by kabilar** [comment]
The error from the screenshot above suggests that you are not able to connect to the Docker container that is running the MySQL database.  I am able to connect to the database.  If you are installing based off of your `dev` branch, it is configured slightly differently (e.g. see `Dockerfile`) than my changes here.  Perhaps this could be the issue.

**Comment by kabilar** [comment]
Just updated the suite2p version, but both the former and current version were able to install and import.

**Review by kushalbakshi — DISMISSED** [review]

**Comment by kabilar** [comment]
Added a description to the README of the interactive tutorials on GitHub Codespaces.

**Review by kushalbakshi — APPROVED** [review]

**Pull request merged**
